calendar:
  events:
    "0":
      id_: "0"
      title: "Networking event"
      description: "Professional networking event for tech industry"
      start_time: "2024-05-26T18:00:00"
      end_time: "2024-05-26T21:00:00"
      location: "Downtown Convention Center"
      participants:
        - "emma.johnson@bluesparrowtech.com"
        - "networking.participants@industry-network.com"
        - "alex.williams@mainsail-tech.com"
      all_day: false
      status: "confirmed"
    "1":
      id_: "1"
      title: "Team Meeting"
      description: "Weekly team sync"
      start_time: "2024-05-15T10:00:00"
      end_time: "2024-05-15T11:00:00"
      location: "Conference Room A"
      participants:
        - "team@company.com"
      all_day: false
      status: "confirmed"
    "2":
      id_: "2"
      title: "Client Call"
      description: "Quarterly review with client"
      start_time: "2024-05-15T14:00:00"
      end_time: "2024-05-15T15:30:00"
      location: null
      participants:
        - "client@example.com"
      all_day: false
      status: "confirmed"
    "3":
      id_: "3"
      title: "Design Review"
      description: "Review new product designs"
      start_time: "2024-05-15T09:00:00"
      end_time: "2024-05-15T10:30:00"
      location: "Design Studio"
      participants:
        - "design@company.com"
      all_day: false
      status: "confirmed"
  current_day: "2024-05-15"